# Generated by Django 5.1.6 on 2025-04-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.IntegerField()),
                ('rating', models.FloatField()),
                ('num_reviews', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('is_bestseller', models.BooleanField(default=False)),
                ('shades_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
